export enum RmActionTypes {
  FETCH_RFI_PENDING = 'FETCH_RFI_PENDING',
  FETCH_RFI_SUCCESS = 'FETCH_RFI_SUCCESS',
  SORT_RFIS_BY_PRIORITY = 'SORT_RFIS_BY_PRIORITY',
  SORT_RFIS_BY_ID = 'SORT_RFIS_BY_ID',
  SORT_RFIS_BY_CUSTOMER = 'SORT_RFIS_BY_CUSTOMER',
  SORT_RFIS_BY_COUNTRY = 'SORT_RFIS_BY_COUNTRY',
  SORT_RFIS_BY_LTIOV = 'SORT_RFIS_BY_LTIOV',
  REPRIORITIZE_RFIS = 'REPRIORITIZE_RFIS'
}
