export enum TgtActionTypes {
  NAVIGATE_TO_TGT_PAGE = 'NAVIGATE_TO_TGT_PAGE',
  RELOAD_TGT_PAGE = 'RELOAD_TGT_PAGE',
  EXIT_TGT_PAGE = 'EXIT_TGT_PAGE',
  UPDATE_RFI_DATE = 'UPDATE_RFI_DATE',
  SHOW_DATE_PLACEHOLDER = 'SHOW_DATE_PLACEHOLDER',
  UPDATE_TGT_SUCCESS = 'UPDATE_TGT_SUCCESS'
}
