spring:
  datasource:
    url: ${PIE_DB_URL}
    username: ${PIE_DB_USERNAME}
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
    out-of-order: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: create-drop
      use-new-id-generator-mappings: false