export enum ActionTypes {
  FETCH_RFI_PENDING = 'FETCH_RFI_PENDING',
  FETCH_RFI_SUCCESS = 'FETCH_RFI_SUCCESS',
  FETCH_MAP_SUCCESS = 'FETCH_MAP_SUCCESS',
  FETCH_PENDING = 'FETCH_FACT_PENDING',
  FETCH_FACT_SUCCESS = 'FETCH_FACT_SUCCESS',
  UPDATE_API = 'UPDATE_API'
}
