export enum RfiActionTypes {
  FETCH_RFI_PENDING = 'FETCH_RFI_PENDING',
  FETCH_RFI_SUCCESS = 'FETCH_RFI_SUCCESS',
  FETCH_RFI_UPDATE = 'FETCH_RFI_UPDATE',
  SORT_RFIS = 'SORT_RFIS',
  REPRIORITIZE_RFIS = 'REPRIORITIZE_RFIS'
}
